catppuccin/vscode-icons

src/associations/files.ts
Hey there 👋 
Tiny PR so we can have support for the latest and greatest!
This PR adds the new `eslint.config.js` "flat config" to `eslint` icon.
https://eslint.org/docs/latest/use/configure/configuration-files-new
=> add eslint flat config file icon

scripts/preview.ts
Makes the preview look nicer :)
Before:
After:
=> build(preview): use retina scaling factor

src/associations/extensions.ts
This PR was motivated by https://github.com/catppuccin/jetbrains-icons/issues/7 (and https://github.com/catppuccin/jetbrains-icons/issues/13).
=> Added mapping for .vue files

LICENSE, README.md
=> chore: add license/readme credits

src/defaults/fileIcons.ts
added file associations mentioned in my previous issues:
#93
#94
=> Resolve issues #93 and #94

icons/css-variables/_root.svg, icons/css-variables/_root_open.svg, icons/frappe/_root.svg, icons/frappe/_root_open.svg, icons/latte/_root.svg, icons/latte/_root_open.svg, icons/macchiato/_root.svg, icons/macchiato/_root_open.svg, icons/mocha/_root.svg, icons/mocha/_root_open.svg, src/utils/themes.ts
=> feat: root folder

src/defaults/fileIcons.ts
https://vitest.dev/guide/#workspaces-support
=> feat: add additional vitest associations

src/defaults/fileIcons.ts
https://github.com/typst/packages#package-format
=> feat(associations): add `typst.toml` manifest file to typst

src/defaults/fileIcons.ts
See https://docs.fastlane.tools/actions/snapshot/
=> feat(associations): add snapfile to fastlane

src/hooks/paths.ts
=> fix: apply settings when using Frappé

icons/css-variables/roblox.svg, icons/frappe/roblox.svg, icons/latte/roblox.svg, icons/macchiato/roblox.svg, icons/mocha/roblox.svg, src/defaults/fileIcons.ts
=> feat: roblox icon

src/defaults/fileIcons.ts
=> feat: .luaurc association

icons/css-variables/poetry-lock.svg, icons/css-variables/python-config.svg, icons/frappe/poetry-lock.svg, icons/frappe/python-config.svg, icons/latte/poetry-lock.svg, icons/latte/python-config.svg, icons/macchiato/poetry-lock.svg, icons/macchiato/python-config.svg, icons/mocha/poetry-lock.svg, icons/mocha/python-config.svg, src/defaults/fileIcons.ts
=> feat: pyproject.toml + poetry.lock icons

src/defaults/folderIcons.ts
=> feat: crates folder association

CONTRIBUTING.md
=> docs: document palettes and compound icons

src/defaults/fileIcons.ts
add missing tauri configuration files, mentioned [here](https://tauri.app/v1/references/configuration-files/#tauri-config)
=> fix(associations): add `tauri.conf.json5` and `Tauri.toml`

src/defaults/fileIcons.ts
Adds these files to Fastlane:
- [`Matchfile`](https://docs.fastlane.tools/actions/match/)
- [`Deliverfile`](https://docs.fastlane.tools/actions/deliver/)
- [`Scanfile`](https://docs.fastlane.tools/actions/scan/)
- [`Gymfile`](https://docs.fastlane.tools/actions/gym/)
=> feat(associations): add fastline built-in action files

.github/workflows/previews.yml
=> ci(previews): revert to creating PR

icons/css-variables/uv.svg, icons/frappe/uv.svg, icons/latte/uv.svg, icons/macchiato/uv.svg, icons/mocha/uv.svg, src/defaults/fileIcons.ts
added an icon for uv.lock file
[reference](https://docs.astral.sh/uv/guides/projects/#uvlock)
=> feat: add uv icon

icons/css-variables/kdl.svg, icons/frappe/kdl.svg, icons/latte/kdl.svg, icons/macchiato/kdl.svg, icons/mocha/kdl.svg, src/defaults/fileIcons.ts
=> feat: kdl icon

icons/css-variables/symlink.svg, icons/frappe/symlink.svg, icons/latte/symlink.svg, icons/macchiato/symlink.svg, icons/mocha/symlink.svg
=> feat: symlink icon (unassociated)

src/defaults/fileIcons.ts
We recently added a [new config file](https://github.com/go-task/task/pull/1982) to Task. This PR associates the config file with the existing Taskfile logo.
=> feat(associations): `.taskrc.yml` files to `taskfile`

README.md
Part of https://github.com/catppuccin/github-file-explorer-icons/issues/109.
=> docs(README): update mention to catppuccin/github-file-explorer-icons

src/defaults/fileIcons.ts
add `for` extension for fortran accoding to [fortran wikipedia article](https://en.wikipedia.org/wiki/Fortran)
=> feat(associations): `for` to `fortran` icon

src/defaults/fileIcons.ts
midi extensions were messed up
=> fix(associations): set file extensions for `midi`

icons/css-variables/3d.svg, icons/frappe/3d.svg, icons/latte/3d.svg, icons/macchiato/3d.svg, icons/mocha/3d.svg, src/defaults/fileIcons.ts
=> feat: 3d icon

src/defaults/fileIcons.ts
=> fix(associations): `prisma` -> `prisma.config.*`
